export const gymData = [
  {
    name: "BFF(Bendemeer)",
    address: "2 Kallang Ave, #01-20 CT hub",
    postal: "339407",
    contact: "9649 4145",
    website: "https://www.bffclimb.com",
    bouldering: true,
    autobelay: true,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "930am-1045pm",
      "930am-1045pm",
      "930am-1045pm",
      "930am-1045pm",
      "930am-1045pm",
      "930am-1045pm",
      "930am-1045pm",
    ],
    slug: "bff-bendemeer",
  },
  {
    name: "BFF(Bukit Timah)",
    address: "896 Dunearn Rd, #02-01D",
    postal: "589472",
    contact: "8368 9214",
    website: "https://www.bffclimb.com",
    bouldering: true,
    autobelay: true,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: {
      playzone: [
        "12:15pm-6:20PM",
        "12:15pm-6:20PM",
        "12:15pm-6:20PM",
        "12:15pm-6:20PM",
        "12:15pm-6:20PM",
        "9:15am-6:40pm",
        "9:15am-6:40pm",
      ],
      boulderzone: [
        "5pm-1am",
        "9:30am-1am",
        "9:30am-1am",
        "9:30am-1am",
        "9:30am-3:15am",
        "7:30am-3:15am",
        "7:30am-10:45pm",
      ],
    },
    slug: "bff-bukit-timah",
  },
  {
    name: "Z-Vertigo",
    address: "170 Upper Bukit Timah Rd, #B2-20B",
    postal: "588179",
    contact: null,
    website: "https://zvertigobouldergym.wixsite.com/zvert",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "3pm-10pm",
      "10am-6pm",
      "10am-6pm",
    ],
    slug: "z-vertigo",
  },
  {
    name: "OYEYO",
    address: "148 Mackenzie Rd",
    postal: "228724",
    contact: "69962095",
    website: "https://oyeyoboulderhome.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "10am-7pm",
      "10am-7pm",
    ],
    slug: "oyeyo",
  },
  {
    name: "Boulder Planet (Sembawang)",
    address: " 604 Sembawang Rd, #B1-22/23 Sembawang Shopping Centre",
    postal: "758459",
    contact: "94692386",
    website: "https://www.boulderplanet.sg/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "10am-9pm",
      "10am-9pm",
    ],
    slug: "boulder-planet-sembawang",
  },
  {
    name: "Boulder Planet (Tai Seng)",
    address: "601 MacPherson Rd, #02-07 Grantral Mall @ MacPherson",
    postal: "368242",
    contact: "94692386",
    website: "https://www.boulderplanet.sg/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "10am-9pm",
      "10am-9pm",
    ],
    slug: "boulder-planet-tai-seng",
  },
  {
    name: "Boulder+ (Chevrons)",
    address: "48 Boon Lay Way, #04-01 The Chevrons",
    postal: "609961",
    contact: "69700116",
    website: "https://www.boulderplusclimbing.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "12:30pm-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "8am-8pm",
      "8am-8pm",
    ],

    slug: "boulderplus-chevrons",
  },
  {
    name: "Boulder+ (Aperia)",
    address: "12 Kallang Ave, #03-17 The Aperia Mall",
    postal: "339511",
    contact: "62827530",
    website: "https://www.boulderplusclimbing.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "12:30pm-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "7:30am-10pm",
      "8am-5:30pm",
      "8am-8pm",
    ],
    slug: "boulderplus-aperia",
  },
  {
    name: "Climb Central Sports Hub",
    address: "12 Kallang Ave, #03-17 The Aperia Mall",
    postal: "397628",
    contact: "67027972",
    website: "https://www.climbcentral.sg/",
    bouldering: true,
    autobelay: true,
    toprope: true,
    lead: true,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "9am-9pm",
      "9am-9pm",
    ],

    slug: "climbcentral-sports-hub",
  },
  {
    name: "Climb Central Novena",
    address: "238 Thomson Rd, #03-23/25",
    postal: "307683",
    contact: "63536885",
    website: "https://www.climbcentral.sg/",
    bouldering: "?",
    autobelay: "?",
    toprope: "?",
    lead: "?",
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "9am-9pm",
      "9am-9pm",
    ],
    slug: "climbcentral-novena",
  },
  {
    name: "Climb Central Funan",
    address: "107 North Bridge Rd, #B2-19/21 Funan",
    postal: "179105",
    contact: "69063918",
    website: "https://www.climbcentral.sg/",
    bouldering: true,
    autobelay: true,
    toprope: true,
    lead: true,
    shower: false,
    watercooler: "?",
    ac: true,
    hours: [
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "9am-9pm",
      "9am-9pm",
    ],
    slug: "climbcentral-funan",
  },
  {
    name: "Climb Central Katong",
    address: "E Coast Rd, #04-01/02 112",
    postal: "428802",
    contact: "69900702",
    website: "https://www.climbcentral.sg/",
    bouldering: "?",
    autobelay: "?",
    toprope: "?",
    lead: "?",
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "11am-11pm",
      "9am-9pm",
      "9am-9pm",
    ],
    slug: "climbcentral-katong",
  },
  {
    name: "The Rock School",
    address: "Our Tampines Hub, 1 Tampines Walk, #02-81",
    postal: "528523",
    contact: "9635 3488",
    website: "https://www.therockschool.sg/",
    bouldering: true,
    autobelay: true,
    toprope: true,
    lead: true,
    shower: false,
    watercooler: "-",
    ac: false,
    hours: [
      "11am-10pm",
      "4:30pm-10pm",
      "11am-10pm",
      "11am-10pm",
      "11am-10pm",
      "9am-9pm",
      "9am-9pm",
    ],
    slug: "the-rock-school",
  },
  {
    name: "b8A",
    address: "03-06, 6 Tampines Street 92, yo:HA Commercial @ Tampines",
    postal: "528893",
    contact: "8023 8313",
    website: "https://www.b8a.sg/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "2pm-10:30pm",
      "2pm-10:30pm",
      "2pm-10:30pm",
      "2pm-10:30pm",
      "2pm-10:30pm",
      "10am-6pm",
      "10am-10pm",
    ],

    slug: "b8a",
  },
  {
    name: "Ark Bloc",
    address: "6 Tebing Ln, #01-05",
    postal: "828835",
    contact: "80221480",
    website: "https://arkbloc.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: false,
    hours: [
      "8pm-12pm, 3pm-10pm",
      "8pm-12pm, 3pm-10pm",
      "8pm-12pm, 3pm-10pm",
      "8pm-12pm, 3pm-10pm",
      "8pm-12pm, 3pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "ark-bloc",
  },
  {
    name: "Boulder Movement (Suntec)",
    address:
      "3 Temasek Boulevard 01-484/485/486 Suntec City Mall, North Wing, Tower One",
    postal: "038983",
    contact: "69939702",
    website: "https://www.boulderm.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "5:30pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "boulder-movement-suntec",
  },
  {
    name: "Boulder Movement (Bugis+)",
    address: " 201 Victoria St, #05 - 07",
    postal: "188067",
    contact: "69939228",
    website: "https://www.boulderm.com/",
    bouldering: true,
    autobelay: true,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "5:30pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "boulder-movement-bugis",
  },
  {
    name: "Boulder Movement (Downtown)",
    address: "6A Shenton Way, #B1-03 Downtown Gallery",
    postal: "068815",
    contact: "6816 6001",
    website: "https://www.boulderm.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "5:30pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "boulder-movement-downtown",
  },
  {
    name: "Boulder Movement (Rochor)",
    address: "2 Serangoon Rd, #02-12 Tekka Place",
    postal: "218227",
    contact: "6993 2100",
    website: "https://www.boulderm.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "5:30pm-10pm",
      "12pm-10pm",
      "9am-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "boulder-movement-rochor",
  },

  {
    name: "Boulder Movement (Tai Seng)",
    address: "18 Tai Seng St, #01-09",
    postal: "539775",
    contact: "6974 7769",
    website: "https://www.boulderm.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: false,
    watercooler: true,
    ac: true,
    hours: [
      "5:30pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "12pm-10pm",
      "10am-10pm",
      "10am-10pm",
    ],
    slug: "boulder-movement-tai-seng",
  },
  {
    name: "Kinetics",
    address: "511 Serangoon Rd",
    postal: "218153",
    contact: "62915045",
    website: "https://www.kineticsclimbing.com.sg/",
    bouldering: true,
    autobelay: true,
    toprope: "yes?",
    lead: false,
    shower: true,
    watercooler: true,
    ac: true,
    hours: [
      "4pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "10am-7pm",
      "10am-7pm",
    ],
    slug: "kinetics",
  },
  {
    name: "Ground Up",
    address: "60 Tessensohn Road CSC@Tessensohn (Level 2)",
    postal: "217664",
    contact: "6292 7701",
    website: "https://www.groundupsg.com/",
    bouldering: true,
    autobelay: true,
    toprope: true,
    lead: true,
    shower: true,
    watercooler: true,
    ac: "partially",
    hours: [
      "5pm-11pm",
      "12pm-11pm",
      "12pm-11pm",
      "12pm-11pm",
      "12pm-10:30pm",
      "10am-9pm",
      "10am-9pm",
    ],
    slug: "ground-up",
  },
  {
    name: "Fit Bloc (Kent Ridge)",
    address: "87 Science Park Dr, #03-02 The Oasis",
    postal: "118260",
    contact: "6612 2046",
    website: "https://fitbloc.com/",
    bouldering: true,
    autobelay: "?",
    toprope: "?",
    lead: "?",
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
    ],
    slug: "fit-bloc-kentridge",
  },
  {
    name: "Fit Bloc (Depot Heights)",
    address: "108 Depot Rd, #02-01 Depot Heights Shopping Centre",
    postal: "100108",
    contact: "6252 9161",
    website: "https://fitbloc.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
    ],
    slug: "fit-bloc-depotheights",
  },
  {
    name: "Arête (By Upwall)",
    address: "5 Changi Business Park Central 1, #02 14/15/16",
    postal: "486038",
    contact: "8028 7028",
    website: "https://upwallclimbing.sg/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
      "9:30am-10pm",
    ],
    slug: "arete",
  },
  {
    name: "Lighthouse Climbing",
    address: "44 Pasir Panjang Road #B-02",
    postal: "118504",
    contact: "9724 4091",
    website: "https://www.lighthouseclimbing.com/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: "?",
    watercooler: "?",
    ac: true,
    hours: [
      "9:30am-10:15pm",
      "9:30am-10:15pm",
      "9:30am-10:15pm",
      "9:30am-10:15pm",
      "9:30am-10:15pm",
      "9:30am-9:15pm",
      "9:30am-9:15pm",
    ],
    slug: "lighthouse",
  },
  {
    name: "Project Send",
    address: "8 Raffles Ave., #02-29 Esplanade Mall",
    postal: "039802",
    contact: "8748 4998",
    website: "https://www.projectsend.co/",
    bouldering: true,
    autobelay: false,
    toprope: false,
    lead: false,
    shower: true,
    watercooler: false,
    ac: true,
    hours: [
      "6:30am-9:30pm",
      "6:30am-9:30pm",
      "6:30am-9:30pm",
      "6:30am-9:30pm",
      "10:30am-1:30m",
      "10:30am-1:30pm",
      "Closed",
    ],
    slug: "project-send",
  },
  {
    name: "T-Hall",
    address: "464 Crawford Lane #01-464",
    postal: "190464",
    contact: "9832 7656",
    website: "https://t-hall.sg/",
    bouldering: true,
    autobelay: true,
    toprope: true,
    lead: true,
    shower: true,
    watercooler: false,
    ac: true,
    hours: [
      "5pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "1pm-10pm",
      "8:30am-8pm",
      "8:30am-8pm",
    ],
    slug: "t-hall",
  },
];

export function fetchGyms() {
  return Object.values(gymData);
}
