export const gymData = [
  {
    name: "BFF(Bendemeer)",
    postal: "339407",
    contact: "9649 4145",
    website: "https://www.bffclimb.com",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: "930am-1045pm",
    slug: "bff-bendemeer",
  },
  {
    name: "BFF(Bukit Timah)",
    postal: "589472",
    contact: "8368 9214",
    website: "www.bffclimb.com",
    bouldering: "yes",
    autobelay: "yes(children-only)",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: {
      playzone: {
        weekday: "12:15pm-6:20Pm",
        weekend: "9:15am-6:40pm",
      },
      boulderzone: {
        mon: "5pm-1am",
        tuestothurs: "9:30am-1am",
        friday: "9:30am-3:15am",
        sat: "7:30am-3:15am",
        sun: "7:30am-10:45pm",
      },
    },
    slug: "bff-bukit-timah",
  },
  {
    name: "OYEYO",
    postal: "228724",
    contact: "69962095",
    website: "www.https://oyeyoboulderhome.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      weekday: "1pm-10pm",
      weekend: "10am-7pm",
    },
    slug: "oyeyo",
  },
  {
    name: "Boulder Planet (Sembawang)",
    postal: "758459",
    contact: "94692386",
    website: "https://www.boulderplanet.sg/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      weekday: "1pm-10pm",
      weekend: "10am-9pm",
    },
    slug: "boulder-planet-sembawang",
  },
  {
    name: "Boulder Planet (Tai Seng)",
    postal: "368242",
    contact: "94692386",
    website: "https://www.boulderplanet.sg/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      weekday: "1pm-10pm",
      weekend: "10am-9pm",
    },
    slug: "boulder-planet-tai-seng",
  },
  {
    name: "Boulder+ (Chevrons)",
    postal: "609961",
    contact: "69700116",
    website: "https://www.boulderplusclimbing.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      monday: "12:30pm-10pm",
      tuestofri: "7:30am-10pm",
      weekend: "8am-8pm",
      PH: "8am-8pm",
    },
    slug: "boulderplus-chevrons",
  },
  {
    name: "Boulder+ (Aperia)",
    postal: "339511",
    contact: "62827530",
    website: "https://www.boulderplusclimbing.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      monday: "12:30pm-10pm",
      tuestofri: "7:30am-10pm",
      sat: "8am-8pm",
      sun: "8am-5:30pm",
      PH: "8am-8pm",
    },
    slug: "boulderplus-aperia",
  },
  {
    name: "Climb Central Sports Hub",
    postal: "397628",
    contact: "67027972",
    website: "https://www.climbcentral.sg/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "yes",
    lead: "yes",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      weekday: "11am-11pm",
      weekend: "9am-9pm",
    },
    slug: "climbcentral-sports-hub",
  },
  {
    name: "Climb Central Novena",
    postal: "307683",
    contact: "63536885",
    website: "https://www.climbcentral.sg/",
    bouldering: "-",
    autobelay: "-",
    toprope: "-",
    lead: "-",
    shower: "-",
    watercooler: "-",
    ac: "yes",
    hours: {
      weekday: "11am-11pm",
      weekend: "9am-9pm",
    },
    slug: "climbcentral-novena",
  },
  {
    name: "Climb Central Funan",
    postal: "179105",
    contact: "69063918",
    website: "https://www.climbcentral.sg/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "yes",
    lead: "yes",
    shower: "no",
    watercooler: "-",
    ac: "yes",
    hours: {
      weekday: "11am-11pm",
      weekend: "9am-9pm",
    },
    slug: "climbcentral-funan",
  },
  {
    name: "Climb Central Katong",
    postal: "428802",
    contact: "69900702",
    website: "https://www.climbcentral.sg/",
    bouldering: "-",
    autobelay: "-",
    toprope: "-",
    lead: "-",
    shower: "-",
    watercooler: "-",
    ac: "yes",
    hours: {
      weekday: "11am-11pm",
      weekend: "9am-9pm",
    },
    slug: "climbcentral-katong",
  },
  {
    name: "The Rock School",
    postal: "528523",
    contact: "9635 3488",
    website: "https://www.therockschool.sg/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "yes",
    lead: "yes",
    shower: "no",
    watercooler: "-",
    ac: "no",
    hours: {
      monday: "11am-10pm",
      tuesday: "4:30pm-10pm",
      wedtofri: "11am-10pm",
      weekend: "9am-9pm",
    },
    slug: "the-rock-school",
  },
  {
    name: "b8A",
    postal: "528893",
    contact: "8023 8313",
    website: "https://www.b8a.sg/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: {
      weekdays: "2pm-10:30pm",
      sat: "10am-6pm",
      sun: "10am-10pm",
    },
    slug: "b8a",
  },
  {
    name: "Ark Bloc",
    postal: "828835",
    contact: "80221480",
    website: "https://arkbloc.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "no",
    hours: {
      weekdays: "8pm-12pm, 3pm-10pm",
      weekends: "10am-10pm",
    },
    slug: "ark-bloc",
  },
  {
    name: "Boulder Movement (Suntec)",
    postal: "038983",
    contact: "69939702",
    website: "https://www.boulderm.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "5:30pm-10pm",
      tuestofri: "12pm-10pm",
      weekends: "10am-10pm",
    },
    slug: "boulder-movement-suntec",
  },
  {
    name: "Boulder Movement (Bugis)",
    postal: "188067",
    contact: "69939228",
    website: "https://www.boulderm.com/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "no",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "5:30pm-10pm",
      tuestofri: "12pm-10pm",
      weekends: "10am-10pm",
    },
    slug: "boulder-movement-bugis",
  },
  {
    name: "Boulder Movement (Downtown)",
    postal: "068815",
    contact: "6816 6001",
    website: "https://www.boulderm.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "5:30pm-10pm",
      tuestofri: "12pm-10pm",
      weekends: "10am-10pm",
    },
    slug: "boulder-movement-downtown",
  },
  {
    name: "Boulder Movement (Rochor)",
    postal: "218227",
    contact: "6993 2100",
    website: "https://www.boulderm.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "5:30pm-10pm",
      tuestofri: "12pm-10pm",
      wed: "9am-10pm",
      weekends: "10am-10pm",
    },
    slug: "boulder-movement-rochor",
  },

  {
    name: "Boulder Movement (Tai Seng)",
    postal: "539775",
    contact: "6974 7769",
    website: "https://www.boulderm.com/",
    bouldering: "yes",
    autobelay: "no",
    toprope: "no",
    lead: "no",
    shower: "no",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "5:30pm-10pm",
      tuestofri: "12pm-10pm",
      weekends: "10am-10pm",
    },
    slug: "boulder-movement-tai-seng",
  },
  {
    name: "Kinetics",
    postal: "218153",
    contact: "62915045",
    website: "https://www.kineticsclimbing.com.sg/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "yes?",
    lead: "no",
    shower: "yes",
    watercooler: "yes",
    ac: "yes",
    hours: {
      mon: "4pm-10pm",
      tuestofri: "1pm-10pm",
      weekends: "10am-7pm",
    },
    slug: "kinetics",
  },
  {
    name: "Ground Up",
    postal: "217664",
    contact: "6292 7701",
    website: "https://www.groundupsg.com/",
    bouldering: "yes",
    autobelay: "yes",
    toprope: "yes",
    lead: "yes",
    shower: "yes",
    watercooler: "yes",
    ac: "partially",
    hours: {
      mon: "5pm-11pm",
      tuestothurs: "12pm-11pm",
      friday: "12pm-10:30pm",
      weekends: "10am-9pm",
    },
    slug: "ground-up",
  },
];

export function fetchGyms() {
  return Object.values(gymData);
}
